name: idle_logout
description: A Flutter package for handling idle user logout
version: 0.1.0+1
homepage: https://pub.dev/packages/idle_logout
repository: https://github.com/noahweasley/idle_logout

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
